name: deploy website
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
      - uses: amondnet/now-deployment@v2
        with:
          zeit-token: ${{ secrets.zeit }} # Required
          now-args: '-A now-staging.json'
      - uses: amondnet/now-deployment@v2
        with:
          zeit-token: ${{ secrets.zeit }} # Required
          now-args: 'https://padi.valehelle.now.sh padi-staging'
      
